# Generated by Django 5.1.4 on 2025-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.IntegerField()),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
